### ISSUE TITLE
Multi gpu model, low GPU utilization

### ISSUE THREAD

**Issue by tensorgpu** [SSSxCCC/AlphaZero-In-Unity#1]
Training using GPU only utilize 1% of my GPU, anybody able to enhance it?

Maybe using keras.utils, multi_gpu_model?

**Comment by tensorgpu** [comment]
使用GPU的训练仅使用我的1％的GPU，谁可以增强它？

也许使用keras.utils，multi_gpu_model？

**Comment by SSSxCCC** [comment]
Most of time is spent in MCTS algorithm while training, so gpu won't help much unless you use a deeper 
neural network.
训练时绝大多时间花费在蒙特卡洛树搜索上面，所以用gpu加速效果不明显，除非用更深的神经网络。
