### ISSUE TITLE
Can alpha-zero learn Bejeweled?

### ISSUE THREAD

**Issue by tensorgpu** [SSSxCCC/AlphaZero-In-Unity#2]
For Bejeweled, after the same colour in a row disappeared, the jewel from row above will move down and if the new row match then they will dissappear too. One action will cause other several moves.

Assuming no new jewel will be generated, just find the best move to solve all the existing jewels.

**Comment by SSSxCCC** [comment]
AlphaZero is designed for two player games, its MCTS algorithm considers not only the good moves for itself but also the good moves for it's opponent. However, Bejeweled is a one player game, AlphaZero can't learn it. If you want to find the best move to play Bejeweled, a tree heuristic search algorithm should be able to solve the problem.

**Comment by tensorgpu** [comment]
Thank you for your suggestion, I will try tree heuristic search.
